<?php

namespace PocztaPolska;

class miejscaPozostawieniaAwizoEnum
{
    const SKRZYNKA_ODDAWCZA = 'SKRZYNKA_ODDAWCZA';
    const DRZWI_MIESZKANIA = 'DRZWI_MIESZKANIA';
    const DRZWI_INNEGO_POMIESZCZENIA = 'DRZWI_INNEGO_POMIESZCZENIA';
    const PRZY_WEJSCIU_NA_POSESJE = 'PRZY_WEJSCIU_NA_POSESJE';
    const SKRYTKA_POCZTOWA = 'SKRYTKA_POCZTOWA';
    const INNE_WIDOCZNE_MIEJSCE = 'INNE_WIDOCZNE_MIEJSCE';
}
