<?php

namespace PocztaPolska;

class podmiotDoreczeniaEnum
{
    const ADRESAT = 'ADRESAT';
    const PELNOLETNI_DOMOWNIK = 'PELNOLETNI_DOMOWNIK';
    const SASIAD = 'SASIAD';
    const DOZORCA_DOMU = 'DOZORCA_DOMU';
    const SOLTYS = 'SOLTYS';
    const ADMINISTRACJA_DOMU = 'ADMINISTRACJA_DOMU';
    const UPOWAZNIONY_PRACOWNIK = 'UPOWAZNIONY_PRACOWNIK';
    const PELNOMOCNIK_POCZTOWY = 'PELNOMOCNIK_POCZTOWY';
    const PRZEDSTAWICIEL_USTAWOWY = 'PRZEDSTAWICIEL_USTAWOWY';
    const PELNOMOCNIK_ADRESATA = 'PELNOMOCNIK_ADRESATA';
    const OSOBA_UPRAWNIONA_DO_REPREZENTACJI = 'OSOBA_UPRAWNIONA_DO_REPREZENTACJI';
    const SKRZYNKA_ODDAWCZA = 'SKRZYNKA_ODDAWCZA';
    const ADRESAT_KTORY_NIE_MOGL = 'ADRESAT_KTORY_NIE_MOGL';
    const OSOBA_UPRAWNIONA_DO_ODBIORU = 'OSOBA_UPRAWNIONA_DO_ODBIORU';
    const DOROSLY_DOMOWNIK = 'DOROSLY_DOMOWNIK';
    const OSOBA_UPOWAZNIONA_DO_ODB_KORESP = 'OSOBA_UPOWAZNIONA_DO_ODB_KORESP';
    const KIEROWNIK_JEDNOSTKI_LUB_UPOWAZNIONY = 'KIEROWNIK_JEDNOSTKI_LUB_UPOWAZNIONY';
    const PRZEDSTAWICIEL_ADRESATA = 'PRZEDSTAWICIEL_ADRESATA';
    const OSOBA_UPOWAZNIONA_DO_REPREZENT_ADRESATA = 'OSOBA_UPOWAZNIONA_DO_REPREZENT_ADRESATA';
    const OSOBA_UPOWAZNIONA_PRZEZ_PRACODAWCE = 'OSOBA_UPOWAZNIONA_PRZEZ_PRACODAWCE';
    const PRZELOZONY_ABW = 'PRZELOZONY_ABW';
    const PRZELOZONY_AW = 'PRZELOZONY_AW';
    const PRZELOZONY_CBA = 'PRZELOZONY_CBA';
    const PRZELOZONY_POLICJI = 'PRZELOZONY_POLICJI';
    const PRZELOZONY_SC = 'PRZELOZONY_SC';
    const PRZELOZONY_SG = 'PRZELOZONY_SG';
    const PRZELOZONY_SKW = 'PRZELOZONY_SKW';
    const PRZELOZONY_SW = 'PRZELOZONY_SW';
    const PRZELOZONY_SWW = 'PRZELOZONY_SWW';
    const PRZELOZONY_ZOLNIERZA = 'PRZELOZONY_ZOLNIERZA';
    const SKRYTKA_POCZTOWA = 'SKRYTKA_POCZTOWA';
    const PROKURENT = 'PROKURENT';
    const ZARZADCA_DOMU = 'ZARZADCA_DOMU';
    const OSOBA_UPOWAZNIONA_PRZEZ_KIER_WIEZIENIA = 'OSOBA_UPOWAZNIONA_PRZEZ_KIER_WIEZIENIA';
}
