<?php

namespace PocztaPolska;

class przyczynaZwrotuEnum
{
    const ODMOWA = 'ODMOWA';
    const ADRESAT_ZMARL = 'ADRESAT_ZMARL';
    const ADRESAT_NIEZNANY = 'ADRESAT_NIEZNANY';
    const ADRESAT_WYPROWADZIL_SIE = 'ADRESAT_WYPROWADZIL_SIE';
    const ADRESAT_NIE_PODJAL = 'ADRESAT_NIE_PODJAL';
    const INNA = 'INNA';
    const ADRES_NIEPELNY = 'ADRES_NIEPELNY';
    const ADRES_BLEDNY = 'ADRES_BLEDNY';
    const ADRES_NIEZGODNY = 'ADRES_NIEZGODNY';
    const ADRES_NIEZNALEZIONY = 'ADRES_NIEZNALEZIONY';
    const ADRESAT_NIE_ZASTANO = 'ADRESAT_NIE_ZASTANO';
    const ADRESAT_NIE_ZGLASZA_SIE = 'ADRESAT_NIE_ZGLASZA_SIE';
    const ADRESAT_NIEOBECNY = 'ADRESAT_NIEOBECNY';
    const ADRESAT_NIEODNALEZIONY = 'ADRESAT_NIEODNALEZIONY';
    const ADRESAT_STRAJKUJE = 'ADRESAT_STRAJKUJE';
    const DO_NADAWCY_NA_POZNIEJ = 'DO_NADAWCY_NA_POZNIEJ';
    const MYLNE_SKIEROWANIE = 'MYLNE_SKIEROWANIE';
    const NADAWCA_ODMOWIL = 'NADAWCA_ODMOWIL';
    const NIE_PODJETO = 'NIE_PODJETO';
    const NIEZGODNE_WYMAGANIA = 'NIEZGODNE_WYMAGANIA';
    const ODMOWA_USZKODZENIA = 'ODMOWA_USZKODZENIA';
    const POBRANIE_NIEZGODNE = 'POBRANIE_NIEZGODNE';
    const USZKODZONA = 'USZKODZONA';
    const ZAMKNIETA_SIEDZIBA = 'ZAMKNIETA_SIEDZIBA';
}
